import {
  ArrowLeft,
  ArrowRightLeft,
  Bell,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  Eye,
  EyeOff,
  Gauge,
  HandIcon,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  MoreHorizontal,
  Pencil,
  Plus,
  RotateCcw,
  Save,
  Settings,
  Undo2,
  User,
} from "lucide-react";

export const Icons = {
  menu: Menu,
  undo2: Undo2,
  eye: Eye,
  eyeOff: EyeOff,
  user: User,
  lock: Lock,
  circleAlert: CircleAlert,
  dashboard: Gauge,
  hand: HandIcon,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  settings: Settings,
  bell: Bell,
  mail: Mail,
  logout: LogOut,
  arrowLeft: ArrowLeft,
  loader2: Loader2,
  save: Save,
  pencil: Pencil,
  plus: Plus,
  moreHorizontal: MoreHorizontal,
  arrowRightLeft: ArrowRightLeft,
  rotateCcw: RotateCcw,
};
